import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const content = JSON.parse(fs.readFileSync(path.join(root, 'docs/legal-content.json'), 'utf8'));
const check = process.argv.includes('--check');
const escape = value => value.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;');
const paragraphs = section => section.paragraphs.map(text => `<p>${escape(text).replaceAll('dreamcabs2025@gmail.com', '<a href="mailto:dreamcabs2025@gmail.com">dreamcabs2025@gmail.com</a>')}</p>`).join('\n');
let failures = 0;
function write(file, text) {
  const target = path.join(root, file);
  const previous = fs.existsSync(target) ? fs.readFileSync(target, 'utf8') : '';
  if (previous === text) return;
  if (check) { console.error(`Outdated legal content: ${file}`); failures++; }
  else fs.writeFileSync(target, text);
}

for (const kind of ['privacy', 'terms']) {
  const sections = content[kind];
  for (const app of ['customer-mobile', 'driver-mobile']) {
    const file = `${app}/src/app/pages/${kind}/${kind}.page.html`;
    const previous = fs.readFileSync(path.join(root, file), 'utf8');
    const header = previous.slice(0, previous.indexOf('<ion-content'))
      .replace(/<span>DPDP Act 2023 · Data Protection<\/span>/g, '<span>Your data and choices</span>')
      .replace(/<span>Driver-Partner Master Agreement<\/span>/g, '<span>Service terms</span>')
      .replace(/<span>Master User Agreement<\/span>/g, '<span>Service terms</span>')
      .replace(/<p class="pg-subtitle">[\s\S]*?<\/p>/, `<p class="pg-subtitle">${kind === 'privacy' ? 'How your information is used and how to manage your privacy.' : 'Booking, payment, safety and account terms for DreamCabs.'}</p>`);
    const body = sections.map((section, i) => `<section class="legal-card" id="${section.id}"><div class="legal-card__header"><span class="legal-num">${String(i + 1).padStart(2, '0')}</span><div><h3>${escape(section.title)}</h3></div></div><div class="legal-card__content">${paragraphs(section)}</div></section>`).join('\n\n');
    write(file, `${header}<ion-content class="pg-content legal-content"><div class="pg-body legal-body">\n<!-- Generated by scripts/generate-legal.mjs from docs/legal-content.json. -->\n${body}\n</div></ion-content>\n`);
    const ts = `${app}/src/app/pages/${kind}/${kind}.page.ts`;
    write(ts, fs.readFileSync(path.join(root, ts), 'utf8').replace(/lastUpdated = '[^']*';/, `lastUpdated = '${content.date}';`));
  }
  const web = `website/${kind === 'privacy' ? 'privacy-policy' : 'terms-conditions'}.html`;
  const previous = fs.readFileSync(path.join(root, web), 'utf8');
  const start = previous.indexOf('<div class="wrap">\n  <div class="doc">');
  const crlfStart = previous.indexOf('<div class="wrap">\r\n  <div class="doc">');
  const bodyStart = start >= 0 ? start : crlfStart;
  const footerStart = previous.indexOf('<footer>');
  if (bodyStart < 0 || footerStart < bodyStart) throw Error(`Cannot locate legal layout: ${web}`);
  const nav = sections.map((section, i) => `<a href="#${section.id}">${i + 1}. ${escape(section.title)}</a>`).join('\n');
  const body = sections.map((section, i) => `<section class="doc-sec"><h2 id="${section.id}">${i + 1}. ${escape(section.title)}</h2>${paragraphs(section)}</section>`).join('\n');
  const head = previous.slice(0, bodyStart).replace(/<p>How DreamCabs collects[^<]*<\/p>/, '<p>How your information is used and how to manage your privacy.</p>');
  write(web, `${head}<div class="wrap">\n  <div class="doc">\n<!-- Generated by scripts/generate-legal.mjs. -->\n<aside class="doc-nav"><h5>On this page</h5>${nav}</aside>\n<div class="doc-body"><span class="updated">Last updated · ${content.date}</span>\n${body}</div>\n</div>\n</div>\n\n${previous.slice(footerStart)}`);
}
const markdown = `# DreamCabs current terms and privacy policy\n\nVersion: ${content.version}. Generated from [legal-content.json](legal-content.json) using \`node scripts/generate-legal.mjs\`.\n\nThese texts supersede the earlier July 2026 documentation bundle for this implementation. The Word document is a historical draft and must not be used as the current publication source. Publication and store approval are separate release steps.\n\n` + ['privacy', 'terms'].map(kind => `# ${kind === 'privacy' ? 'Privacy Policy' : 'Terms and Conditions'}\n\n` + content[kind].map(section => `## ${section.title}\n\n${section.paragraphs.join('\n\n')}\n`).join('\n')).join('\n');
write('docs/DreamCabs-Legal-Terms-and-Privacy-Policy-Final.md', markdown);
if (failures) process.exitCode = 1;
else console.log(check ? 'Legal content is synchronized.' : 'Generated website, mobile and Markdown legal content.');
